### ISSUE TITLE
Reproducing the edge prediction result.

### ISSUE THREAD

**Issue by Jarvis-K** [laclauc/FairGraph#1]
Hi, I am trying to predict the edge in g1(specified and generated as in Appendix). The result is as following:  
![image](https://user-images.githubusercontent.com/18642955/126642169-5674c222-dedb-4d0b-807c-b6afacf5a1fb.png)
It seems like the repairing procedure makes the edge un-predictable.
Would u like to share your script for edge prediction?

p.s. my edge prediction is following the [Node2Vec](https://colab.research.google.com/github/stellargraph/stellargraph/blob/master/demos/link-prediction/node2vec-link-prediction.ipynb#scrollTo=N7_CC8PIxkwv).

**Comment by laclauc** [comment]
Hello Jarvis, yes indeed for the synthetic graphs we observed similar results, probably due to the small size + the density of the new obtained network. Next week, I'll share the scripts used for of edge prediction for real-worlk network used in the paper as well as a script to handle the synthetic graphs.

**Comment by Jarvis-K** [comment]
That will be a great help.
I am looking forward to your updates.

**Comment by Jarvis-K** [comment]
> Hello Jarvis, yes indeed for the synthetic graphs we observed similar results, probably due to the small size + the density of the new obtained network. Next week, I'll share the scripts used for of edge prediction for real-worlk network used in the paper as well as a script to handle the synthetic graphs.
A friendly remind of scripts updating in case you forget about that. Will these scripts be updated in a few days?

**Comment by Jarvis-K** [comment]
> Hello Jarvis, yes indeed for the synthetic graphs we observed similar results, probably due to the small size + the density of the new obtained network. Next week, I'll share the scripts used for of edge prediction for real-worlk network used in the paper as well as a script to handle the synthetic graphs.

A friendly remind of scripts updating in case you forget about that. Will these scripts be updated in a few days?

**Comment by laclauc** [comment]
Hello, I've uploaded a demo for polblogs. The reason for the results that you otabined is that very small weights obtained in the corrected adjacency matrix need to be set to 0. I usually choose a threshold for the "very small" in a way that allow me to retrieve a repaired graph with the same density as the original one. Hope that helps.
